from typing import Any

class cached_property:
    __doc__: Any
    func: Any
    def __init__(self, func: Any) -> None: ...
    def __get__(self, obj: Any, cls: Any) -> Any: ...

class class_property:
    func: Any
    def __init__(self, func: Any) -> None: ...
    def __get__(self, instance: Any, cls: Any) -> Any: ...

class class_cached_property:
    func: Any
    def __init__(self, func: Any) -> None: ...
    def __get__(self, obj: Any, cls: Any) -> Any: ...
