name: Code Quality
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  code-quality:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]
        poetry-version: [1.0, 1.1.13]
        os: [ubuntu-18.04, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Check formatting with Black
        run: poetry run black pony-stubs --check

      - name: Check linting with Pylint
        run: poetry run pylint pony-stubs

      - name: Check typing with Mypy
        run: poetry run mypy pony-stubs

      - name: Check typing with Pyright
        run: poetry run pyright pony-stubs
